name: reinvent_scoring
channels:
  - openeye
  - rdkit
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _low_priority=1.0
  - _py-xgboost-mutex=2.0
  - _pytorch_select=0.1
  - aiohttp=3.6.2
  - anaconda-client=1.7.2
  - asn1crypto=1.3.0
  - async-timeout=3.0.1
  - attrs=19.3.0
  - beautifulsoup4=4.9.1
  - blas=1.0
  - bleach=3.1.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.6.20
  - cairo=1.14.12
  - certifi=2020.6.20
  - cffi=1.14.0
  - chardet=3.0.4
  - clyent=1.2.2
  - cmarkgfm=0.4.2
  - colorama=0.4.3
  - conda=4.8.3
  - conda-build=3.18.11
  - conda-package-handling=1.6.1
  - cryptography=2.3.1
  - cudatoolkit=10.1.243
  - dacite=1.5.1
  - dataclasses=0.7
  - dbus=1.13.6
  - decorator=4.4.2
  - dill=0.3.2
  - docutils=0.16
  - entrypoints=0.3
  - expat=2.2.9
  - filelock=3.0.12
  - fontconfig=2.13.0
  - freetype=2.10.2
  - future=0.18.2
  - glib=2.63.1
  - glob2=0.7
  - icu=58.2
  - idna=2.10
  - idna_ssl=1.1.0
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - intel-openmp=2020.1
  - ipython_genutils=0.2.0
  - jeepney=0.4.3
  - jinja2=2.11.2
  - joblib=0.16.0
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter_core=4.6.3
  - keyring=21.2.1
  - lcms2=2.11
  - libarchive=3.3.2
  - libboost=1.67.0
  - libedit=3.1
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.5.0
  - liblief=0.10.1
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxgboost=1.1.1
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - more-itertools=8.4.0
  - multidict=4.7.5
  - multiprocess=0.70.10
  - nbformat=5.0.7
  - ncurses=6.0
  - nest-asyncio=1.4.0
  - ninja=1.9.0
  - numpy=1.17.3
  - numpy-base=1.17.3
  - olefile=0.46
  - openeye-toolkits=2019.10.2
  - openssl=1.0.2u
  - packaging=20.4
  - pandas=1.0.5
  - patchelf=0.11
  - pathos=0.2.6
  - pcre=8.44
  - pillow=7.2.0
  - pip=20.1.1
  - pixman=0.40.0
  - pkginfo=1.5.0.1
  - pluggy=0.13.1
  - pox=0.2.8
  - ppft=1.6.6.1
  - psutil=5.7.0
  - py=1.9.0
  - py-boost=1.67.0
  - py-lief=0.10.1
  - py-xgboost=1.1.1
  - pycosat=0.6.3
  - pycparser=2.20
  - pygments=2.6.1
  - pyopenssl=19.0.0
  - pyparsing=2.4.7
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - pytest=5.4.3
  - python=3.6.5
  - python-dateutil=2.8.1
  - python-libarchive-c=2.9
  - python_abi=3.6
  - pytorch=1.3.1
  - pytz=2020.1
  - pyyaml=5.3.1
  - rdkit=2019.09.3.0
  - readline=7.0
  - readme_renderer=24.0
  - requests=2.24.0
  - requests-toolbelt=0.9.1
  - rfc3986=1.4.0
  - ripgrep=11.0.2
  - ruamel_yaml=0.15.87
  - scikit-learn=0.21.3
  - scipy=1.5.0
  - secretstorage=3.1.2
  - setuptools=49.2.0
  - six=1.15.0
  - soupsieve=2.0.1
  - sqlite=3.23.1
  - tk=8.6.10
  - tqdm=4.47.0
  - traitlets=4.3.3
  - twine=3.2.0
  - typing_extensions=3.7.4.2
  - urllib3=1.25.9
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.34.2
  - xgboost=1.1.1
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.4.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - reinvent-chemistry==0.0.32
